apiVersion: v1
kind: Pod
metadata:
  name: nginx-pod
  namespace: default
  labels:
    mwam.com/min-containerd-version: "v1.5.2"
    mwam.com/min-kubelet-version: "v1.21.1"
    mwam.com/no-sensitive-mount: "true"
spec:
  containers:
    - name: "nginx-pod"
      image: "nginx:latest"
      ports:
        - name: "http"
          containerPort: 80
